# Generated by Django 6.1.1 on 2026-09-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_auto_20170307_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, help_text='Foto del producto obtenida de la página de compra.'),
        ),
    ]
