# Generated by Django 6.1.1 on 2026-09-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Visible para visitantes no registrados.'),
        ),
    ]
