# Generated by Django 6.1.1 on 2026-09-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_gift_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
