# Generated by Django 6.1.1 on 2026-09-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_alter_gift_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
